# Generated by Django 3.1.7 on 2021-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=5)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=300)),
                ('keg_size', models.PositiveIntegerField()),
                ('keg_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
