# Generated by Django 3.1.7 on 2021-03-26 12:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_kegs', models.PositiveIntegerField()),
                ('price_per_keg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(default=datetime.datetime(2021, 3, 26, 12, 3, 46, 176236))),
                ('customer', models.CharField(max_length=100)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='beers.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
